version: '3.8'

services:
  secret-room-frontend:
    image: secret-room-frontend:prod
    container_name: secret-room-frontend-prod
    restart: unless-stopped
    ports:
      - "5002:4000"
    environment:
      - NODE_ENV=production
      - SSR_API_URL=http://host.docker.internal:9092/api/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
